# Auto-report action script, 3 times a day

name: Auto-report action

on: 
  push:
    branches:
      - master
  schedule:
    - cron: '15 12,14,16,18,20 * * *'

jobs:
  report:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        sudo apt install tesseract-ocr -y
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pillow pytesseract requests
    - name: Run report script
      env:
        STUID: ${{ secrets.Stuid }}
        PASSWORD: ${{ secrets.Password }}
        EMER_PERSON: ${{ secrets.Emer_person }}
        EMER_RELA: ${{ secrets.Emer_rela }}
        EMER_PHONE: ${{ secrets.Emer_phone }}
        DORM_BUILDING: ${{secrets.dorm_Building}}
        DORM: ${{secrets.dorm}}
        BIGDATA_URL : ${{ secrets.BIGDATA_URL }}
        ANKANG_URL : ${{ secrets.ANKANG_URL }}
        GID : ${{secrets.GID}}
        SIGN : ${{secrets.SIGN}}
      run: |
        python report.py data_atschool.json "$STUID" "$PASSWORD" "$EMER_PERSON" "$EMER_RELA" "$EMER_PHONE" "$DORM_BUILDING" "$DORM" "$BIGDATA_URL" "$ANKANG_URL" "$GID" "$SIGN"