# Auto-report action script, 3 times a day

name: Auto-report action

on: 
  push:
    branches:
      - master
  schedule:
    - cron: '10 4,11,17,23 * * *'

jobs:
  report:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        sudo apt install tesseract-ocr -y
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pillow pytesseract requests
    - name: Run report script
      run: |
        python report.py data_atschool.json "$STUID" "$PASSWORD" "$EMER_PERSON" "$EMER_RELA" "$EMER_PHONE" "DORM_BUILDING" "DORM"
